### ISSUE TITLE
Input lag

### ISSUE THREAD

**Issue by therezor** [awcodes/filament-tiptap-editor#121] opened 2023-06-20 17:49 UTC
During every input editor send request to server which cause a freeze for ~1 sec. Thats make it unusable.
https://youtu.be/s0hDSGIRU_Q

**Comment by awcodes** [comment] 2023-06-20 19:02
Did you set the field to be reactive?

**Comment by therezor** [comment] 2023-06-20 20:09
> Did you set the field to be reactive?

No
```
TiptapEditor::make('description')
                            ->label(__('attributes.description'))
                            ->profile('barebone')
                            ->columnSpan('full'),
```                    

Even with `    ->stateBindingModifiers(['defer']),` same issue

**Comment by therezor** [comment] 2023-06-20 20:22
Requests are triggered from here
```
      onBlur() {
                    _this.updatedAt = Date.now();
                    _this.focused = false;
                    _this.state = _this.getFormattedContent();
                    _this.$wire.set(_this.statePath, _this.getFormattedContent());
                },

**Comment by awcodes** [comment] 2023-06-20 21:15
Ok, I'll double check tomorrow, but no one else has reported this as an issue.

**Comment by awcodes** [comment] 2023-06-21 21:38
So, unfortunately, I can't remove this as it needs to be available on blur for validation if it's set to reactive or lazy. And there's not a lot I can do about slow connections. 

I'm open to ideas if you have any, or even a PR.

I'm going to close the issue for now. Feel free to reopen if you need to.

**Closed as not planned** 2023-06-21 21:38 UTC

**Comment by monteduro** [comment] 2024-01-15 10:57
It seems that the problem persists when there is a large amount of text in the editor. Even if I'm on M1, the problem is really annoying.

One possible solution that I've tested is to set a timeout on updating the state (file /resources/js/plugin.js), even with 300ms. This will prevent a delay and slow performance for those who type fast.

```javascript
onUpdate({editor}) {
  _this.updatedAt = Date.now();
  clearTimeout(_this.timeOut);
  _this.timeOut = setTimeout(function(){
    _this.state = editor.isEmpty ? null : editor.getJSON();
  },300);
},
```

To replicate the issue just paste a large amount of text in the editor and try to type.

**Comment by awcodes** [comment] 2024-01-15 19:01
Don't use live() on rich text fields. There is 0 actual reason to hit the server every time a user types a letter. It is bad practice and should be avoided for exactly this type of reason. :)

**Comment by monteduro** [comment] 2024-01-15 21:34
Certainly. In fact, I'm not using live or reactive in any of those fields; it is something that happened at the JS level, when the editor has a lot of text.
